language: c
cache: ccache
os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.2
compiler:
  - clang
  - gcc
script:
  - ulimit -a
  - ulimit -n 512
  - ulimit -a
matrix:
  exclude:
    - os: osx
      compiler: gcc