name: test

on:
  #schedule:
  #  - cron: "0 */6 * * *"
  push:
  pull_request:

jobs:
  x86_64:
    name: "mingw-w64-x86_64 All"
    runs-on: windows-latest
    timeout-minutes: 960
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Get msys2
        shell: powershell
        run: Invoke-WebRequest -UseBasicParsing -OutFile msys2.tar.xz -Uri https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.tar.xz
      - name: Extract msys2
        shell: powershell
        run: 7x x -aoa msys2.tar.xz
      - name: Run msys2
        run: msys64/usr/bin/bash.exe -lc 'exit'
      - name: Run test script
        shell: msys64/usr/bin/bash.exe --noprofile --norc -eo pipefail{0}
        run: ./test.sh
